### ISSUE TITLE
determine heuristics for geocoding bbls

### ISSUE THREAD

**Issue by clhenrick** [aepyornis/DOB-Jobs#4]
Options I can think of are:
- using various MapPLUTO datasets (seems prone to errors)
- adding the geometry values via NodeJS with PG and NYC GeoClient API

**Comment by clhenrick** [comment]
**note:** the wacky house numbers are an issue if we try to use the geo-client API:

``` sql
dob_jobs=# select count(house) from dob_jobs_2014 where house like '%-%';
 count 
-------
 15412
(1 row)
```

looks like there are some dates in there too:

``` sql
dob_jobs=# select house from dob_jobs_2014 where house like '%-%' limit 50;
  house   
----------
 147-43
 147-43
 65-50
 40-28
 42-35
 150-20
 79-17
 42-35
 243-09
 40-28
 40-28
 40-28
 39-24
 42-35
 146-19
 40-28
 146-11
 146-11
 42-35
 136-21
 144-51
 61-01
 84-16
 65-50
 61-01
 247-08
 61-01
 45-19
 22-34
 22-28
 79-17
 22-30
 79-17
 51-35
 22-32
 79-17
 144-35
 40-28
 61-35
 40-28
 2-Nov-14
 2-Nov-14
 40-28
 40-28
 2-Nov-14
 61-35
 30-41
 42-35
 92-41
 40-28
(50 rows)
```

**Comment by clhenrick** [comment]
this query filters out the numbers that are correctly formatted:

``` sql
select cast(house as float) from dob_jobs_2014 
where house not like '%-%' and house not like '%A' and house not like '%G%' and house not ilike '%c%'
and house not ilike '%f%' and house not ilike '%e%' and house not ilike '%d%' and house not ilike '%j%'
and house not ilike '%b%' and house not ilike '%h%' and house not ilike '%/%' and house not ilike '% %'
and house not ilike '%y%' and house not ilike '%t%'  and house not ilike '%u%' and house not ilike '%p%';
```

but it drops about 16,000 rows

**Comment by clhenrick** [comment]
Okay so this does the trick:

``` sql
update dob_jobs_2014 set house = cast(house as float) where house like '%.%';
```

(You may want to run this query after importing the data via node-postgres)

**Comment by aepyornis** [comment]
I ended up geocoding the BBLs through a join with PLUTO. It's true, there were errors (about 5%), but it worked well enough. I think it's a better result that using the the geoclient API. We could try to run the ones that didn't work through the geoclient and see if we get results that way. 

In ArcGIS I did the following steps: pluto -> FEATURE to POINT -> convert to WGS84 -> create Lat and Lng fields -> calculate geometry -> convert BBL field to string -> filter to only these column: lat, lng, bbl -> export as table (csv).

That could easily be done in QGIS to avoid using non-free software. 

I then used [this](https://github.com/aepyornis/DOB-Jobs/blob/master/sql/geocode.sql) script to update the data. 

The ones that didn't get geocoded remain in the table, but they won't show up on the map. I can upload the CSV file too if you'd like it.

**Comment by clhenrick** [comment]
Hi Ziggy, sounds good. The NYC Geoclient API also has a method where you can look up addresses by BBL. I think 5% error of the total isn't bad though and using PLUTO seems sufficient.

RE: the ArcGIS method can also be replicated in PostGIS / CartoDB. Might be worth writing a script for that too given the frequency at which Pluto gets updated.
